gText_Birch_Welcome::
	.string "Hi! Welcome to Nuzlockers's Emerald!\p"
	.string "This is an Enhancement hack\n"
	.string "with QoL and difficulty changes.\p"
	.string "This enforces a 'hardcore' Nuzlocke\n"
	.string "ruleset:\p"
	.string "1) If a pokemon faints, it stays\n"
	.string "fainted forever. It cannot be\l"
	.string "revived via items or centers.\p"
	.string "2) You can only receive one\n"
	.string "pokemon per location.  This is\l"
	.string "defined by the 'Met at' location\l"
	.string "in the summary screen.\p"
	.string "3) You must play on SET mode.\n"
	.string "This means that the game will not ask\l"
	.string "if you want to switch POKéMON before\l"
	.string "a trainer sends out theirs.\p"
	.string "4) You cannot use the bag during\n"
	.string "trainer battles.\p"
	.string "5) Gym Leaders and other bosses\n"
	.string "will not let you overlevel them.\p"
	.string "Let me know if you run into\n"
	.string "any problems. Have fun! -MATT\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
